### PR TITLE
Archive repository

### PR DESCRIPTION
**Pull request by svrnm**
Contributes to https://github.com/open-telemetry/community/issues/2453

I would need someone to translate the text to Chinese as well, such that the note is available in both languages

### CODE REVIEW

**Comment by flc1125** [comment]
> [!IMPORTANT]
> 此仓库已归档，将不再接受任何更新，包括不限于如：接受问题处理、拉取请求。
>
> 关于  OpenTelemetry 文档和网站的本地化的资料，可访问 [opentelemetry.io](https://github.com/open-telemetry/opentelemetry.io)

**Comment by svrnm** [comment]
thanks @flc1125 ! Can you take another look?

**Comment by flc1125** [comment]
I think it's great!

**Review by reyang — APPROVED** [review]
The translation looks good to me.

**Comment by svrnm** [comment]
> The translation looks good to me.

Thanks!

Can someone merge the PR?

**Comment by reyang** [comment]
> > The translation looks good to me.
> 
> Thanks!
> 
> Can someone merge the PR?

@svrnm do you mean 1) wait for enough approvals and merge it OR 2) use some superpower to merge it (considering we're archiving the repo anyways) - I can help on 2) but not 1)

image

**Review by flc1125 — APPROVED** [review]

**Comment by flc1125** [comment]
😁 Haha, I thought my approval could also...

**Comment by trask** [comment]
here are the current approvers: @addname @sunface @tensorchen @tydhot

as @reyang mentioned, both he and I can override the approval requirement and merge the PR if you'd like

**Review by addname — APPROVED** [review]

**Comment by reyang** [comment]
Thanks @addname! @svrnm I think you're all set now.

**Comment by addname** [comment]
😀

**Pull request merged**
