### PR TITLE
补充了metrics-api，attribute-and-label-naming.md的文档翻译

### PR DESCRIPTION
**Pull request by 13667285528**
Added Chinese translation of some documents

assets/opentelemetry-roadmap-cn.jpg
specification/common/attribute-and-label-naming.md
specification/metrics/semantic_conventions/README.md
specification/metrics/api.md

### CODE REVIEW

**Comment by 13667285528** [comment]
签署协议后重新提交

**Comment by 13667285528** [comment]
签署协议后重新提交

**Comment by 13667285528** [comment]
签署协议后，重新登陆然后提交

**Comment by 13667285528** [comment]
再次签署协议后，重新登陆然后提交

**Review by sunface — APPROVED** [review]
thanks :)

**Comment by 13667285528** [comment]
I signed it

**Comment by 13667285528** [comment]
I signed it

**Pull request closed without merging**
